apiVersion: apps/v1
kind: Deployment
metadata:
  name: adaptive-learning-backend
  namespace: neuropath
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adaptive-learning-backend
  template:
    metadata:
      labels:
        app: adaptive-learning-backend
    spec:
      containers:
        - name: adaptive-learning-backend
          image: neuropath-backend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

