apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: neuropath
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app: postgres
